// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjz72_KXofDDakxSe0fyKEDNob0513Mps',
    appId: '1:375032871251:web:1638ce6111796d0a0a49a6',
    messagingSenderId: '375032871251',
    projectId: 'my-map-tracker-project',
    authDomain: 'my-map-tracker-project.firebaseapp.com',
    storageBucket: 'my-map-tracker-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHzAPkqKH-vJzn3vYL0dgPnx11UsOadQ',
    appId: '1:375032871251:android:7f0be5a019b064b90a49a6',
    messagingSenderId: '375032871251',
    projectId: 'my-map-tracker-project',
    storageBucket: 'my-map-tracker-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuX5LNfptdpf0Fa8RrxllduFol3TDpdiM',
    appId: '1:375032871251:ios:27da340c3bf2d49b0a49a6',
    messagingSenderId: '375032871251',
    projectId: 'my-map-tracker-project',
    storageBucket: 'my-map-tracker-project.firebasestorage.app',
    iosBundleId: 'com.example.mapTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuX5LNfptdpf0Fa8RrxllduFol3TDpdiM',
    appId: '1:375032871251:ios:27da340c3bf2d49b0a49a6',
    messagingSenderId: '375032871251',
    projectId: 'my-map-tracker-project',
    storageBucket: 'my-map-tracker-project.firebasestorage.app',
    iosBundleId: 'com.example.mapTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjz72_KXofDDakxSe0fyKEDNob0513Mps',
    appId: '1:375032871251:web:28483fab8a7fb43e0a49a6',
    messagingSenderId: '375032871251',
    projectId: 'my-map-tracker-project',
    authDomain: 'my-map-tracker-project.firebaseapp.com',
    storageBucket: 'my-map-tracker-project.firebasestorage.app',
  );
}
